// var shopItemsData = [
//      {
//           id: "1",
//           name: "Casual Shirt",
//           price: 45,
//           desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
//           img: "images/img-1.jpg",
//      },
//      {
//           id: "2",
//           name: "Office Shirt",
//           price: 100,
//           desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
//           img: "images/img-2.jpg",
//      },
//      {
//           id: "3",
//           name: "T Shirt",
//           price: 25,
//           desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
//           img: "images/img-3.jpg",
//      },
//      {
//           id: "4",
//           name: "Mens Suit",
//           price: 300,
//           desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
//           img: "images/img-4.jpg",
//      },
//      {
//           id: "5",
//           name: "Mens Suit",
//           price: 300,
//           desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
//           img: "./images/prod (1).jpg",
//      },
//      {
//           id: "6",
//           name: "Mens Suit",
//           price: 300,
//           desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
//           img: "./images/prod (2).jpg",
//      },
//      {
//           id: "7",
//           name: "Remax RPP-96",
//           price: 300,
//           desc: "Amazfit GTS 2 Mini ( 1.55 ) Bluetooth Smartwatch -Flamingo",
//           img: "./images/prod (3).jpg",
//      },
//      {
//           id: "8",
//           name: "Silicone Sport",
//           price: 300,
//           desc: "Remax RPP-96 Power Bank - 10000mAh - Black",
//           img: "./images/prod (4).jpg",
//      },
//      {
//           id: "9",
//           name: "Mobile Phone",
//           price: 300,
//           desc: "Nokia - 1.8-inch Dual SIM Mobile Phone - Dark Grey",
//           img: "./images/prod (5).jpg",
//      },
// ]; export {shopItemsData}